#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Keys
#

export AWS_ACCESS_KEY=AKIAJEL5AF2CUGOR34GQ
export AWS_SECRET_KEY=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
export SIDEKIQ_CONSOLE_USER=foreman
export SIDEKIQ_CONSOLE_PASSWORD=ZQnm9dnRHt4jJq
export IRONMQ_AUTH_TOKEN=c7m653wTMqoEhBJQozh7fkGuEm9Ex4IXr8uUBmiGyoxhW84C0jFoctf9xzvlOJMX
export FULLFABRIC_AUTH_TOKEN=5af57fc097deec085451befe1f6b1f43c033838dd677dadd3045f4b51971a568
export ULTRAHOOK_API_KEY=nXpoqoAEmmmmuio0TCAtxrnZddUVwUqP
# export SENDGRID_USERNAME=ff-imperial
# export SENDGRID_PASSWORD=7MGuskJQGqiMB2xbjjUFCnXV

#
# Path
#

# Added by the Heroku Toolbelt
export PATH=/usr/local/heroku/bin:$PATH

# Setting PATH for Go
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Setting PATH for Python 2.7
export PATH=/Library/Frameworks/Python.framework/Versions/2.7/bin:$PATH

# Setting PATH for Python 3.5
export PATH=/Library/Frameworks/Python.framework/Versions/3.5/bin:$PATH

# export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/
